name: Build e2xgrader image and activate a specific mode

on:
  workflow_dispatch:
    inputs: 
      force_build:
        description: If the build should be forced even if there are no changes
        type: boolean
        required: false
        default: false
      base_image_name:
        description: The name of the base image to build from
        type: string
        required: true
      base_image_tag:
        description: The tag of the base image to build from
        type: string
        required: false
        default: latest
      image_tag:
        description: The tag of the image we build. E.g. latest
        type: string
        required: false
        default: latest
      e2xgrader_mode:
        description: Which e2xgrader mode to activate
        type: choice
        required: true
        options:
        - student
        - student_exam
        - teacher
      e2xgrader_version:
        description: If a specific e2xgrader version should be installed from PyPi
        type: string
        required: false
        default: ""
      install_from_repo:
        description: If e2xgrader should be install from github instead of PyPi
        type: boolean
        required: false
        default: false
      e2xgrader_branch:
        description: Which e2xgrader branch or tag to install from. Only takes effect if install_from_repo is not "false"
        type: string
        required: false
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pull base image
        if: ${{ inputs.force_build }}
        env:
          BASE_IMAGE: ${{ inputs.base_image_name }}:${{ input.base_image_tag }}
        run: |
          docker pull $BASE_IMAGE
      - name: Set image tag
        run: |
          if [ "${{ inputs.e2xgrader_mode }}" == "student_exam" ]; then
            echo "IMAGE_TAG=exam-${{ inputs.base_image_name }}:${{ inputs.image_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ inputs.e2xgrader_mode }}-${{ inputs.base_image_name }}:${{ inputs.image_tag }}" >> $GITHUB_ENV
          fi
      - name: Build image
        if: ${{ inputs.force_build }}
        env:
          FROM_REPO: ${{ inputs.install_from_repo }}
          E2XGRADER_MODE: ${{ inputs.e2xgrader_mode }}
          E2XGRADER_VERSION: ${{ inputs.e2xgrader_version }}
          E2XGRADER_BRANCH: ${{ inputs.e2xgrader_branch }}
          BASE_IMAGE: ${{ inputs.base_image_name }}:${{ inputs.base_image_tag }}
          IMAGE_PATH: "images/e2xgrader-notebook"
        run: |
          echo "Building image: $IMAGE_TAG"
          cd $IMAGE_PATH
          docker build -t $IMAGE_TAG . \
            --build-arg IMAGE_SOURCE=$BASE_IMAGE \
            --build-arg E2XGRADER_MODE=$E2XGRADER_MODE \
            --build-arg E2XGRADER_VERSION=$E2XGRADER_VERSION \
            --build-arg FROM_REPO=$FROM_REPO \
            --build-arg E2XGRADER_BRANCH=$E2XGRADER_BRANCH \
            --progress=plain
          docker images
            
            
            
        
      
      
