name: Build e2xgrader image for all modes

on:
  workflow_dispatch:
    inputs: 
      force_build:
        description: If the build should be forced even if there are no changes
        type: boolean
        required: false
        default: false
      base_image_name:
        description: The name of the base image to build from
        type: string
        required: true
      base_image_tag:
        description: The tag of the base image to build from
        type: string
        required: false
        default: latest
      image_name:
        description: The name of the image we build.
        type: string
        required: true
      image_tag:
        description: The tag of the image we build. E.g. latest
        type: string
        required: false
        default: latest
      e2xgrader_version:
        description: If a specific e2xgrader version should be installed from PyPi
        type: string
        required: false
        default: ""
      install_from_repo:
        description: If e2xgrader should be install from github instead of PyPi
        type: boolean
        required: false
        default: false
      e2xgrader_branch:
        description: Which e2xgrader branch or tag to install from. Only takes effect if install_from_repo is not "false"
        type: string
        required: false
        default: "main"

jobs:
  build:
    strategy:
      matrix:
        e2xgrader_mode: [student, student_exam, teacher]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set image tag
        id: set_image_tag
        run: |
          if [ "${{ matrix.e2xgrader_mode }}" == "student_exam" ]; then
            echo "image_tag=${{ inputs.image_name }}-exam:${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ inputs.image_name }}-${{ matrix.e2xgrader_mode }}:${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
          fi
      - name: Print image tag
        id: print_image_tag
        run: |
          echo ${{ steps.set_image_tag.outputs.image_tag }}
      - name: Build Docker image
        if: ${{ inputs.force_build }}
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: images/e2xgrader-notebook
          push: false
          tags: ${{ steps.set_image_tag.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=${{ inputs.base_image_name }}:${{ inputs.base_image_tag }}
            E2XGRADER_MODE=${{ matrix.e2xgrader_mode }}
            E2XGRADER_VERSION=${{ inputs.e2xgrader_version }}
            E2XGRADER_BRANCH=${{ inputs.e2xgrader_branch }}
      - name: List images
        if: ${{ inputs.force_build }}
        run: |
          docker images
            
            
            
        
      
      
